version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_URL: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-mydb}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-jwt-secret-key}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-jwt-refresh-key}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5002:5000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data: {}
  redis_data: {}
