version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_URL: postgres://user:password@db:5432/mydb
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-jwt-secret-key}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-jwt-refresh-key}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  redis_data:
